/**
 * Accepted league match needs — a time and place two players have agreed on.
 *
 * This is scheduling only. League fixtures are generated by admin and scoring runs
 * separately through the fixture-based log-result flow, so an accepted need never
 * becomes a `league_matches` row and cannot be read from /leagues/{id}/fixtures.
 *
 * Before this existed the accepted match had nowhere to appear. Every match-need
 * listing filters to status "open" — myNeeds (routes/leagues.js), and the browse and
 * suggestion lists (league_match_needs.js) — so the moment the accept flipped the row
 * to "confirmed" it dropped out of all of them. The player saw the card vanish and
 * nothing take its place, which read as the accept having failed.
 *
 * The rows come from the general matches list instead, which does not exclude league
 * matches and enriches each one with its participants' profiles. Both players are
 * returned it: the host is added to match_participants as "hosting" when the need is
 * posted and the accepter as "confirmed" on accept, and the participant join does not
 * filter on participant status.
 *
 * Lives here rather than in either page because both the league detail page and the
 * league dashboard render it, and the opponent-derivation and league-scoping rules
 * below are exactly the kind of thing that drifts when copied.
 */

export type ScheduledLeagueMatch = {
  id: number | string;
  leagueId: number | string | null;
  hostId: number | string | null;
  opponentName: string;
  startDateTime: string | null;
  timezone: string | null;
  location: string | null;
  /** True when the viewer posted the need; false when they accepted someone else's. */
  viewerIsHost: boolean;
};

// Statuses meaning "this player is no longer part of the match". `left` is set by
// POST /matches/:id/leave; `removed` by the host removing a player.
const WITHDRAWN_STATUSES = new Set(["left", "removed", "cancelled", "declined"]);

type RawParticipant = {
  player_id?: number | string;
  status?: string;
  profile?: { full_name?: string | null } | null;
};

/**
 * Map one row from GET /matches into a scheduled-match view model.
 * Returns null for anything that is not a league match, so callers can filter.
 */
export const toScheduledLeagueMatch = (
  raw: unknown,
  viewerId: unknown,
): ScheduledLeagueMatch | null => {
  if (!raw || typeof raw !== "object") return null;
  const match = raw as Record<string, unknown>;
  if (match.is_league_match !== true) return null;

  // GET /matches?filter=my joins match_participants on player_id with NO filter on
  // participant status, so a match you withdrew from still comes back as "yours". The
  // match usually drops out anyway because leaving reopens it, but that only holds for
  // 1v1 league matches — and a row you can still press Cancel on, for a match you have
  // already left, is worse than an absent one. Read your own row and drop it.
  const viewerParticipant = (Array.isArray(match.participants)
    ? (match.participants as RawParticipant[])
    : []
  ).find((participant) => String(participant?.player_id) === String(viewerId));
  if (viewerParticipant && WITHDRAWN_STATUSES.has(String(viewerParticipant.status))) {
    return null;
  }

  const hostId = (match.host_id as number | string | undefined) ?? null;
  const viewerIsHost = viewerId != null && String(hostId) === String(viewerId);
  const participants = Array.isArray(match.participants)
    ? (match.participants as RawParticipant[])
    : [];
  // The opponent is whoever is not the viewer. Comparing as strings because ids arrive
  // as numbers from the API and often as strings from stored auth payloads.
  const opponent =
    participants.find((participant) => String(participant.player_id) !== String(viewerId)) ?? null;

  return {
    id: match.id as number | string,
    leagueId: (match.league_id as number | string | undefined) ?? null,
    hostId,
    opponentName: opponent?.profile?.full_name?.trim() || "League player",
    startDateTime: (match.start_date_time as string | null) ?? null,
    timezone: (match.timezone as string | null) ?? null,
    location: (match.location_text as string | null) ?? null,
    viewerIsHost,
  };
};

/**
 * Filter a GET /matches payload down to this league's scheduled matches, soonest first.
 * `filter=my` spans every league the player belongs to, hence the league scoping here.
 */
export const buildScheduledLeagueMatches = ({
  matches,
  leagueId,
  viewerId,
}: {
  matches: unknown[];
  leagueId: number | string | null | undefined;
  viewerId: unknown;
}): ScheduledLeagueMatch[] =>
  matches
    .map((match) => toScheduledLeagueMatch(match, viewerId))
    .filter((match): match is ScheduledLeagueMatch => match !== null)
    .filter((match) => String(match.leagueId ?? "") === String(leagueId ?? ""))
    .sort((a, b) => {
      // Undated matches sort last rather than to 1970.
      const aTime = a.startDateTime ? new Date(a.startDateTime).getTime() : Number.MAX_SAFE_INTEGER;
      const bTime = b.startDateTime ? new Date(b.startDateTime).getTime() : Number.MAX_SAFE_INTEGER;
      return aTime - bTime;
    });
